import { octokit, getRepoConfig } from "@/lib/roy/integrations/github";
import { generateText } from "ai";
import { openai } from "@ai-sdk/openai";

const ENGINEERING_SYSTEM_PROMPT = `You are an expert full-stack engineer. Generate clean, production-ready code that follows best practices.

When generating code:
- Use TypeScript/React best practices
- Include proper error handling
- Add helpful comments where needed
- Follow the existing codebase patterns
- Return valid JSON array: [{ path: string, content: string }]`;

async function getBaseSha(owner: string, repo: string) {
  "use step";
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: "heads/main",
  });
  return ref.object.sha;
}

async function createBranch(
  owner: string,
  repo: string,
  branchName: string,
  sha: string
) {
  "use step";
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha,
  });
}

async function createTree(
  owner: string,
  repo: string,
  baseSha: string,
  files: Array<{ path: string; content: string }>
) {
  "use step";
  const { data: newTree } = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseSha,
    tree: files.map((f) => ({
      path: f.path,
      mode: "100644",
      type: "blob",
      content: f.content,
    })),
  });
  return newTree;
}

async function createPullRequest(
  owner: string,
  repo: string,
  branchName: string,
  task: string
) {
  "use step";
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: task,
    head: branchName,
    base: "main",
    body: `Generated by Roy\n\n${task}`,
    draft: true,
  });
  return pr;
}

export async function engineeringWorkflow(input: {
  task: string;
  targetFiles?: string[];
}) {
  "use workflow";
  const codeGen = await generateText({
    model: openai("gpt-4o"),
    system: ENGINEERING_SYSTEM_PROMPT,
    prompt: `Task: ${input.task}
${input.targetFiles ? `Target files: ${input.targetFiles.join(", ")}` : ""}

Generate file changes as JSON array: [{ path: string, content: string }]`,
  });

  let files: Array<{ path: string; content: string }>;
  try {
    files = JSON.parse(codeGen.text);
  } catch (error) {
    // If parsing fails, try to extract JSON from markdown code blocks
    const jsonMatch = codeGen.text.match(/```(?:json)?\s*(\[[\s\S]*?\])/);
    if (jsonMatch) {
      files = JSON.parse(jsonMatch[1]);
    } else {
      throw new Error(
        `Failed to parse code generation result: ${codeGen.text}`
      );
    }
  }

  const { owner, repo } = getRepoConfig();
  const baseSha = await getBaseSha(owner, repo);
  const branchName = `roy/${Date.now()}`;

  await createBranch(owner, repo, branchName, baseSha);
  const newTree = await createTree(owner, repo, baseSha, files);

  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo,
    message: `feat: ${input.task}`,
    tree: newTree.sha,
    parents: [baseSha],
  });

  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
    sha: commit.sha,
  });

  const pr = await createPullRequest(owner, repo, branchName, input.task);

  return {
    type: "engineering",
    prUrl: pr.html_url,
    prNumber: pr.number,
    branch: branchName,
    files: files.map((f) => f.path),
  };
}
